-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1059
--   at:        2017-10-19 14:16:40 GMT+01:00
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE album (
    title        VARCHAR(50) NOT NULL,
    artist       VARCHAR(15),
    year         VARCHAR(4),
    created_at   DATE,
    updated_at   DATE
);

ALTER TABLE album ADD CONSTRAINT album_pk PRIMARY KEY ( title );

CREATE TABLE cart (
    created_at   DATE,
    updated_at   DATE,
    users_id     INTEGER NOT NULL
);

ALTER TABLE cart ADD CONSTRAINT cart_pk PRIMARY KEY ( users_id );

CREATE TABLE cart_songs (
    songs_title   VARCHAR(50) NOT NULL,
    cart_id       INTEGER NOT NULL
);

ALTER TABLE cart_songs ADD CONSTRAINT cart_songs_pk PRIMARY KEY ( songs_title );

CREATE TABLE genre (
    title         VARCHAR(50) NOT NULL,
    description   VARCHAR(500) NOT NULL,
    created_at    DATE,
    updated_at    DATE
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( title );

CREATE TABLE libraries (
    title         VARCHAR(25) NOT NULL,
    description   VARCHAR(250),
    created_at    DATE,
    updated_at    DATE,
    users_id      INTEGER NOT NULL
);

CREATE UNIQUE INDEX libraries__idx ON
    libraries ( users_id ASC );

ALTER TABLE libraries ADD CONSTRAINT libraries_pk PRIMARY KEY ( title,users_id );

CREATE TABLE library_songs (
    songs_title          VARCHAR(50) NOT NULL,
    libraries_title      VARCHAR(25) NOT NULL,
    libraries_users_id   INTEGER NOT NULL
);

ALTER TABLE library_songs
    ADD CONSTRAINT library_songs_pk PRIMARY KEY ( songs_title,libraries_title,libraries_users_id );

CREATE TABLE playlist (
    title         VARCHAR(30) NOT NULL,
    description   VARCHAR(250),
    users_id      INTEGER NOT NULL
);

ALTER TABLE playlist ADD CONSTRAINT playlist_pk PRIMARY KEY ( title,users_id );

CREATE TABLE playlist_songs (
    songs_title      VARCHAR(50) NOT NULL,
    playlist_id      INTEGER NOT NULL,
    playlist_title   VARCHAR(30) NOT NULL
);

ALTER TABLE playlist_songs
    ADD CONSTRAINT playlist_songs_pk PRIMARY KEY ( songs_title,playlist_title,playlist_id );

CREATE TABLE quality (
    name      VARCHAR(25) NOT NULL,
    bitrate   VARCHAR(5),
    format    VARCHAR(6)
);

ALTER TABLE quality ADD CONSTRAINT quality_pk PRIMARY KEY ( name );

CREATE TABLE songs (
    title          VARCHAR(50) NOT NULL,
    artiest        VARCHAR(50),
    length         VARCHAR(40),
    created_at     DATE,
    updated_at     DATE,
    album_title    VARCHAR(50) NOT NULL,
    genre_title    VARCHAR(50) NOT NULL,
    quality_name   VARCHAR(25) NOT NULL
);

ALTER TABLE songs ADD CONSTRAINT songs_pk PRIMARY KEY ( title );

CREATE TABLE users (
    id           INTEGER NOT NULL,
    first_name   VARCHAR(25),
    last_name    VARCHAR(25),
    password     VARCHAR(64),
    is_admin     CHAR(1),
    created_at   DATE,
    updated_at   DATE
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( id );

ALTER TABLE cart_songs
    ADD CONSTRAINT cart_songs_cart_fk FOREIGN KEY ( cart_id )
        REFERENCES cart ( users_id );

ALTER TABLE cart_songs
    ADD CONSTRAINT cart_songs_songs_fk FOREIGN KEY ( songs_title )
        REFERENCES songs ( title );

ALTER TABLE cart
    ADD CONSTRAINT cart_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE libraries
    ADD CONSTRAINT libraries_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE library_songs
    ADD CONSTRAINT library_songs_libraries_fk FOREIGN KEY ( libraries_title,libraries_users_id )
        REFERENCES libraries ( title,users_id );

ALTER TABLE library_songs
    ADD CONSTRAINT library_songs_songs_fk FOREIGN KEY ( songs_title )
        REFERENCES songs ( title );

ALTER TABLE playlist_songs
    ADD CONSTRAINT playlist_songs_playlist_fk FOREIGN KEY ( playlist_title,playlist_id )
        REFERENCES playlist ( title,users_id );

ALTER TABLE playlist_songs
    ADD CONSTRAINT playlist_songs_songs_fk FOREIGN KEY ( songs_title )
        REFERENCES songs ( title );

ALTER TABLE playlist
    ADD CONSTRAINT playlist_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE songs
    ADD CONSTRAINT songs_album_fk FOREIGN KEY ( album_title )
        REFERENCES album ( title );

ALTER TABLE songs
    ADD CONSTRAINT songs_genre_fk FOREIGN KEY ( genre_title )
        REFERENCES genre ( title );

ALTER TABLE songs
    ADD CONSTRAINT songs_quality_fk FOREIGN KEY ( quality_name )
        REFERENCES quality ( name );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             1
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
