
INSERT INTO USERS(USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,IS_ADMIN,CREATED_AT,UPDATED_AT)
VALUES('supertatje','tatje@test.nl','Henk','Tatje','dit wordt een hashed password',0,'2017-10-19','2017-10-19');

INSERT INTO USERS(USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,IS_ADMIN,CREATED_AT,UPDATED_AT)
VALUES('testuser1','test@test.nl','Jan','Test','dit wordt een hashed password',0,'2017-10-19','2017-10-19');

INSERT INTO USERS(USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,IS_ADMIN,CREATED_AT,UPDATED_AT)
VALUES('testuser2','test@test.nl','klaas','Test','dit wordt een hashed password',0,'2017-10-19','2017-10-19');

INSERT INTO USERS(USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,IS_ADMIN,CREATED_AT,UPDATED_AT)
VALUES('testuser3','test@test.nl','Karst','Test','dit wordt een hashed password',0,'2017-10-19','2017-10-19');

INSERT INTO USERS(USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,IS_ADMIN,CREATED_AT,UPDATED_AT)
VALUES('testuser4','test@test.nl','Jan','Klaasesn','dit wordt een hashed password',0,'2017-10-19','2017-10-19');


INSERT INTO QUALITY(NAME,BITRATE,FORMAT)
VALUES('low quality mp3',95,'.mp3');

INSERT INTO QUALITY(NAME,BITRATE,FORMAT)
VALUES('low quality wma',95,'.wma');

INSERT INTO QUALITY(NAME,BITRATE,FORMAT)
VALUES('medium quality mp3',128,'.mp3');


INSERT INTO QUALITY(NAME,BITRATE,FORMAT)
VALUES('medium quality wma',195,'.wma');


INSERT INTO QUALITY(NAME,BITRATE,FORMAT)
VALUES('high quality mp3',320,'.mp3');


INSERT INTO ALBUM(TITLE,ARTIST,YEAR,CREATED_AT, UPDATED_AT)
VALUES('VANVAR','VANVAR','2007','2017-10-19','2017-10-19');


INSERT INTO GENRE (TITLE,DESCRIPTION,CREATED_AT, UPDATED_AT)
VALUES('SOMEWHAT HARD ROCK','THIS MAKES YOUR EARS BLEED ONLY A BIT','2017-10-19','2017-10-19');

INSERT INTO GENRE (TITLE,DESCRIPTION,CREATED_AT, UPDATED_AT)
VALUES('HARDER ROCK','THIS MAKES YOUR EARS BLEED QUITE A BIT','2017-10-19','2017-10-19');

INSERT INTO GENRE (TITLE,DESCRIPTION,CREATED_AT, UPDATED_AT)
VALUES('BRITISH ROCK','THIS MAKES YOUR EARS BLEED QUITE A BIT, BUT IN A BRITISH WAY','2017-10-19','2017-10-19');

INSERT INTO GENRE (TITLE,DESCRIPTION,CREATED_AT, UPDATED_AT)
VALUES('DUTCH ROCK','THIS MAKES YOUR EARS BLEED AN INSANE AMOUNT, ITS QUITE HORRIBLE','2017-10-19','2017-10-19');

INSERT INTO GENRE (TITLE,DESCRIPTION,CREATED_AT, UPDATED_AT)
VALUES('HARD ROCK','THIS KIND OF MUSIC IS USED BY KOREA IN INTEREGATION','2017-10-19','2017-10-19');

INSERT INTO GENRE (TITLE,DESCRIPTION,CREATED_AT, UPDATED_AT)
VALUES('EDM','Dance to it','2017-10-19','2017-10-19');


INSERT INTO SONGS(TITLE, ARTIEST,LENGTH,CREATED_AT,UPDATED_AT,ALBUM_TITLE,GENRE_TITLE,QUALITY_NAME,PRICE,description,file_location)
VALUES('Blimp','<a href="https://soundcloud.com/vanvarmusic">VANVAR</a>','1:25.5','2017-10-19','2017-10-19','VANVAR','EDM','high quality mp3',17.12,'wow','songs/Blimp.mp3');

INSERT INTO SONGS(TITLE, ARTIEST,LENGTH,CREATED_AT,UPDATED_AT,ALBUM_TITLE,GENRE_TITLE,QUALITY_NAME,PRICE,description,file_location)
VALUES('The Tiger','<a href="https://soundcloud.com/vanvarmusic">VANVAR</a>','1:25.5','2017-10-19','2017-10-19','VANVAR','EDM','high quality mp3',17.12,'wow','songs/The-Tiger.mp3');

INSERT INTO SONGS(TITLE, ARTIEST,LENGTH,CREATED_AT,UPDATED_AT,ALBUM_TITLE,GENRE_TITLE,QUALITY_NAME,PRICE,description,file_location)
VALUES('My Game','<a href="https://soundcloud.com/vanvarmusic">VANVAR</a>','1:25.5','2017-10-19','2017-10-19','VANVAR','EDM','high quality mp3',17.12,'wow','songs/My-Game.mp3');

INSERT INTO SONGS(TITLE, ARTIEST,LENGTH,CREATED_AT,UPDATED_AT,ALBUM_TITLE,GENRE_TITLE,QUALITY_NAME,PRICE,description,file_location)
VALUES('Dreaming','<a href="https://soundcloud.com/vanvarmusic">VANVAR</a>','1:25.5','2017-10-19','2017-10-19','VANVAR','EDM','high quality mp3',17.12,'wow','songs/Dreaming.mp3');

INSERT INTO SONGS(TITLE, ARTIEST,LENGTH,CREATED_AT,UPDATED_AT,ALBUM_TITLE,GENRE_TITLE,QUALITY_NAME,PRICE,description,file_location)
VALUES('Dance to it','<a href="https://soundcloud.com/vanvarmusic">VANVAR</a>','1:25.5','2017-10-19','2017-10-19','VANVAR','EDM','high quality mp3',17.12,'wow','songs/Dance-to-it.mp3');

INSERT INTO SONGS(TITLE, ARTIEST,LENGTH,CREATED_AT,UPDATED_AT,ALBUM_TITLE,GENRE_TITLE,QUALITY_NAME,PRICE,description,file_location)
VALUES('Its You','<a href="https://soundcloud.com/vanvarmusic">VANVAR</a>','1:25.5','2017-10-19','2017-10-19','VANVAR','EDM','high quality mp3',17.12,'wow','songs/Its-You.mp3');


INSERT INTO CART(CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('2017-10-19','2017-10-19',1);

INSERT INTO CART(CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('2017-10-19','2017-10-19',2);

INSERT INTO CART(CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('2017-10-19','2017-10-19',3);

INSERT INTO CART(CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('2017-10-19','2017-10-19',4);

INSERT INTO CART(CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('2017-10-19','2017-10-19',5);

-- TESTDATA CART_SONGS---
INSERT INTO CART_SONGS(SONGS_TITLE,CART_ID)
VALUES('Blimp', 1);

INSERT INTO CART_SONGS(SONGS_TITLE,CART_ID)
VALUES('Dreaming', 1);

INSERT INTO CART_SONGS(SONGS_TITLE,CART_ID)
VALUES('Blimp', 3);

INSERT INTO CART_SONGS(SONGS_TITLE,CART_ID)
VALUES('Dreaming', 3);

INSERT INTO CART_SONGS(SONGS_TITLE,CART_ID)
VALUES('Blimp', 5);
 
 
INSERT INTO LIBRARIES(TITLE,DESCRIPTION,CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('MAIN LIBRARY','','2017-10-19','2017-10-19',1);

INSERT INTO LIBRARIES(TITLE,DESCRIPTION,CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('MAIN LIBRARY','','2017-10-19','2017-10-19',2);

INSERT INTO LIBRARIES(TITLE,DESCRIPTION,CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('MAIN LIBRARY','','2017-10-19','2017-10-19',3);

INSERT INTO LIBRARIES(TITLE,DESCRIPTION,CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('MAIN LIBRARY','','2017-10-19','2017-10-19',4);

INSERT INTO LIBRARIES(TITLE,DESCRIPTION,CREATED_AT,UPDATED_AT,USERS_ID)
VALUES('MAIN LIBRARY','','2017-10-19','2017-10-19',5);

INSERT INTO LIBRARY_SONGS(SONGS_TITLE,LIBRARIES_TITLE,LIBRARIES_USERS_ID)
VALUES('Dreaming','MAIN LIBRARY',1);

INSERT INTO LIBRARY_SONGS(SONGS_TITLE,LIBRARIES_TITLE,LIBRARIES_USERS_ID)
VALUES('Blimp','MAIN LIBRARY',1);

INSERT INTO LIBRARY_SONGS(SONGS_TITLE,LIBRARIES_TITLE,LIBRARIES_USERS_ID)
VALUES('Dreaming','MAIN LIBRARY',3);

INSERT INTO LIBRARY_SONGS(SONGS_TITLE,LIBRARIES_TITLE,LIBRARIES_USERS_ID)
VALUES('Blimp','MAIN LIBRARY',5);

INSERT INTO LIBRARY_SONGS(SONGS_TITLE,LIBRARIES_TITLE,LIBRARIES_USERS_ID)
VALUES('Dreaming','MAIN LIBRARY',1);

